# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0002_auto_20181220_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
