# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0003_auto_20181220_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pk']},
        ),
    ]
